### PR TITLE
Fixes the color of the search button in navbar 

### PR DESCRIPTION
**Pull request by sumayaSalihs**
Fixes the color of the search button in navbar to make it look better

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@sumayaSalihs, I'm sorry that I've not been able to get back on this earlier. I was quite busy with work lately.

I've made some changes to css in search wrapper. Please take a pull and try this out locally.

We could make some changes with the colour of the search image. You might also wanna revert the change in content_script.js

**Comment by sumayaSalihs** [comment]
@Roshanjossey sure, will work on it.

**Comment by Roshanjossey** [comment]
@sumayaSalihs, I guess, the only thing remaining here is to improve the colors of search button.

I played around with the colors a bit. I ended up with this

```
    <g fill="none" fill-rule="evenodd">
        <use fill="#f5f5f5" xlink:href="#a" /><!--This colors the entire thing-->
        <rect stroke="#c1c5ca" x=".5" y=".5" width="18" height="19" rx="3" /><!--This color the edges-->
        <path fill="#c1c5ca" d="M11.76 5.979l-3.8 9.079h-.91l3.78-9.08z" /> <!--this color the "/"-->
    </g>

```

I felt like this went with the old color palette well. Please do let me know your thoughts on this.

**Comment by sumayaSalihs** [comment]
@Roshanjossey will work on the color.

**Comment by Roshanjossey** [comment]
Looks good @sumayaSalihs. I'm merging 🎉 ✨

Thank you so much for your contribution 🙇

**Pull request merged**
